language: java

jdk:
  - oraclejdk9
  - oraclejdk11

os:
  - linux

before_script:
  - ./gradlew build
  - mkdir ./tmp
  - echo 1 > ./tmp/1
  - echo 2 > ./tmp/2

script:
  - ./gradlew check
  - java -jar ./build/libs/merge_sort-1.0.jar -i ./tmp/1 ./tmp/2 ./tmp/out

